interface INotify {
  sendNotification(): any;
}

// Design Patterns : Dependency Injection
function CalculatePowerReturn(notifier : INotify) {
    //............
    //............
    //............
    //............
    //............

    //............
    //............
    //............
    //............
    //............
    notifier.sendNotification();

    //............
    //............
    //............
    //............

}

class EmailSender implements INotify {
    sendNotification(){
        // Send Email
    }
}

let email = new EmailSender();

CalculatePowerReturn(email);